server.port: 9296

spring:
  application:
    name: CLOUD-CONFIG-SERVICE
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PSURESH192/default-config-server
          clone-on-start: true
